### ISSUE TITLE
Unable to re-enter Crypt

### ISSUE THREAD

**Issue by ThomasRitschel** [Pyrdacor/Ambermoon-Advanced#2]
After I have been in the crypt near the Alchemist tower, I'm unable to re-enter it anymore after leaving it. Only way to get in again is to load the savegame with non-advanced version 1.0...I forgot which version I used when entering it the first time.

**Comment by Pyrdacor** [comment]
Unfortunately I can't reproduce this.

**Comment by ThomasRitschel** [comment]
I just tested again, and its still not working. Should I send you the savefiles?

**Comment by Pyrdacor** [comment]
Yes would be great

**Comment by ThomasRitschel** [comment]
es ist der aktuelle Spielstand, in der Liste der letzte (Nr.8., glaub ich)


Zitat von Pyrdacor ***@***.***>:

> Yes would be great
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/Pyrdacor/Ambermoon-Advanced/issues/2#issuecomment-1315670322
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>



{
  "UsePatcher": false,
  "PatcherTimeout": null,
  "WindowX": null,
  "WindowY": null,
  "MonitorIndex": null,
  "Width": 1680,
  "Height": 1050,
  "FullscreenWidth": 1920,
  "FullscreenHeight": 1080,
  "Fullscreen": true,
  "UseDataPath": false,
  "DataPath": "C:\\Users\\Thomas\\Desktop\\spiele\\Ambermoon.net-Windows-Standalone\\Ambermoon.net",
  "SaveOption": 0,
  "GameVersionIndex": 2,
  "LegacyMode": false,
  "Music": true,
  "Volume": 100,
  "ExternalMusic": false,
  "BattleSpeed": 100,
  "CacheMusic": true,
  "AutoDerune": true,
  "EnableCheats": false,
  "ShowButtonTooltips": true,
  "GraphicFilter": 2,
  "GraphicFilterOverlay": 0,
  "Effects": 0,
  "ShowPlayerStatsTooltips": true,
  "ShowPyrdacorLogo": true,
  "ShowThalionLogo": true,
  "ShowFloor": true,
  "ShowCeiling": true,
  "ExtendedSavegameSlots": true,
  "AdditionalSavegameSlots": [
    {
      "GameVersionName": "german",
      "Names": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "ContinueSavegameSlot": 0
    },
    {
      "GameVersionName": "english",
      "Names": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "ContinueSavegameSlot": 0
    },
    {
      "GameVersionName": "advanced_german",
      "Names": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "ContinueSavegameSlot": 8
    },
    {
      "GameVersionName": "advanced_english",
      "Names": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "ContinueSavegameSlot": 0
    },
    {
      "GameVersionName": "external",
      "Names": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "ContinueSavegameSlot": 0
    }
  ],
  "ShowSaveLoadMessage": false
}

**Comment by Pyrdacor** [comment]
Thanks. I will have a look at it tomorrow.

**Comment by Pyrdacor** [comment]
Maybe I'm blind but I can't find any attachment. Can you send me the saves via mail: trobt@web.de Also the one I should repair for the "Tierhandlung" in #1 . Thanks

**Comment by ThomasRitschel** [comment]
I've sent to this EMail address. The most recent savegame (Nr.8) shows  
both issues (Tierhandlung and Crypt) and I would like to keep this one  
to continue. Ignore the rest of the savegames.

Zitat von Pyrdacor ***@***.***>:

**Comment by Pyrdacor** [comment]
I guess if you answer to the github mails it won't include your attachments. Please send it as a normal Email manually.

**Comment by ThomasRitschel** [comment]
Ive already sent to ***@***.*** a couple of hours ago, didnt you receive it?

Zitat von Pyrdacor ***@***.***>:

**Comment by Pyrdacor** [comment]
Ah sorry, have missed that one because it ended in another folder. Will fix it tomorrow.

**Comment by Pyrdacor** [comment]
[Save.08.zip](https://github.com/Pyrdacor/Ambermoon-Advanced/files/10218251/Save.08.zip)

Sorry that it took so long. Here is your fixed savegame. Both issues are fixed.
