### ISSUE TITLE
Minor wording issue in Dor Kiredon

### ISSUE THREAD

**Issue by macce2** [Pyrdacor/Ambermoon-Advanced#21]
In the tavern you meet Darbog, who says:
"Welcome adventurers! Even HERE in DOR GRESTIN 
we heard of your arrival!"

IMHO that should be corrected.
Maybe just removing the word "here" from the sentence Darbog says
should be enough !?

**Comment by Pyrdacor** [comment]
This is in Dor Kiredon? Then this is a bug. Maybe the NPCs was meant to be in Dor Greetin instead? Have to investigate this.

**Comment by macce2** [comment]
Yes, it does occur when in Dor Kiredon.
I guess this must propably be present in original Ambermoon also (!?);
but I decided to add thios here, just because I'm playhing and testing
this version ! (Ambermoon Advanced English v. 1.03)

**Comment by Pyrdacor** [comment]
Well in the current version there is no change on the forest moon or Morag. So everything you find there is in the original as well.

**Comment by macce2** [comment]
There are two buildings with doors in Dor Kiredon,
that cannot be entered.
Is that on purpose...!?
In the case that those buildings can be entered somehow, 
please don't spoil too much!

**Comment by Pyrdacor** [comment]
Those are not supposed to enter and there is no way to do so.

**Comment by macce2** [comment]
Ok, nice to know that !
Maybe we(you)'ll find some use for them in the upcoming releases ! 
I could start trying to get some realistic ideas for those too...!?!
