### ISSUE TITLE
Wording in Torles Logbuch

### ISSUE THREAD

**Issue by iancrossfield** [Pyrdacor/Ambermoon-Advanced#3]
Two small suggested changes in wording:

First, in the phrase, "to avoid crushing into the eastern rocky coast,"  the word "crushing" should perhaps be "crashing" -- though perhaps instead you mean "to avoid being crushed on the eastern rocky coast."  To give it a truly nautical feel, a true 'sea dog' might say: "...to avoid being driven onto the rocky Hoimon coast underneath our lee."

Second, the phrase "I could hold myself on the steering wheel with all my strength..." might be slightly more clear as, "With all my strength I was able to only barely keep hold of the steering wheel, but many...."   

Looking forward to exploring Capt. Torle's sightings!

**Comment by Pyrdacor** [comment]
Thanks. I am no native speaker so I am very thankful for any suggestions.

**Comment by Pyrdacor** [comment]
I integrated your suggestions into the data for the second episode.
