### ISSUE TITLE
Nelvin has incorrect Charisma value

### ISSUE THREAD

**Issue by macce2** [Pyrdacor/Ambermoon-Advanced#8]
I had made a Savegame in Orc cave.
It was there that I first noticed 
Nelvin's Charisma value: 111 / 70.
This must be incorrect value, right..?!
Currently, I'm unable to tell more 
precisely, right when the value
was changed to that.
The Charisma value of Nelvin was
valid and noticeably lower in the
earlier Savegame state I had made.

**Comment by Pyrdacor** [comment]
Do you have some item equipped which grants charisma? For example the golden brooch which grants +50 charisma?

**Comment by Pyrdacor** [comment]
The game shows "actual value + bonus value" so if you have 61 charisma and the brooch equipped it would be 111. Unequipping it should show 61 again.

**Comment by macce2** [comment]
Oh I'm sorry, I think it must be the brooch .

**Comment by Pyrdacor** [comment]
No worries. The max value only shows the maximum you can achieve through normal increases like potions. That's why it still shows 70.
